apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-html-app
  template:
    metadata:
      labels:
        app: sample-html-app
    spec:
      containers:
      - name: sample-html-app
        image: durgesh191/sample-html-app:latest
        ports:
        - containerPort: 80
