apiVersion: v1
kind: Service
metadata:
  name: sample-html-app
spec:
  selector:
    app: ample-html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
  type: nodePort
